// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE5zzz-0npGsXxznzeh19bZisljGc17Sw',
    appId: '1:489654701677:web:4c223270ed84228cb93964',
    messagingSenderId: '489654701677',
    projectId: 'pokemon-battle-logger',
    authDomain: 'pokemon-battle-logger.firebaseapp.com',
    storageBucket: 'pokemon-battle-logger.appspot.com',
    measurementId: 'G-51FMZD25EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29zJI2l6ZWjmZMegI8VqByNef4txF5Z4',
    appId: '1:489654701677:android:029e9add80233327b93964',
    messagingSenderId: '489654701677',
    projectId: 'pokemon-battle-logger',
    storageBucket: 'pokemon-battle-logger.appspot.com',
  );
}
